<div id="cadou-form-modal" style="display:none">
<form action="" method="POST">
        <label for="name">Name: </label>
        <input type="text" id="name" name="name"/><br>
        <label for="email">Email: </label>
        <input type="text" id="email" name="email"/><br>
        <label for="birthdate">Birth date: </label>
        <input type="text" id="birthdate" name="birthdate"/><br>
        <label for="address">Address: </label>
        <textarea id="address" name="address" rows="7" cols="30"></textarea>
</form>
</div>